### ISSUE TITLE
Fuzzy Matching: error

### ISSUE THREAD

**Issue by jdecorte** [hogent-cads/AI_MDM_Prototype#48]
![image](https://user-images.githubusercontent.com/6873055/236791642-e96a80b2-60f1-426d-9e94-1c1689c89497.png)

**Comment by jdecorte** [comment]
With resto file.

**Comment by slievens** [comment]
Deze fout lijkt er ook uit. Was waarschijnlijk hetzelfde als https://github.com/hogent-cads/AI_MDM_Prototype/issues/56
