### ISSUE TITLE
Reload van dataset met zelfde naam werkt niet

### ISSUE THREAD

**Issue by jdecorte** [hogent-cads/AI_MDM_Prototype#54]
Scenario:

- "Browse files" en kies dataset
- klik op kruisje naast naam file
- Wijzig data in csv-file
- "Browse files" en kies zelfde file (dus met gewijzigde inhoud)
- Wijzigingen zijn niet overgenomen.

Workaround: tool afsluiten en herstarten.

**Comment by slievens** [comment]
Lijkt nu te werken.
